
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  Point,
  PublicKey,
  Wallet,
} from '@aztec/aztec.js';
import TranscientEscrowContractArtifactJson from './TranscientEscrow.json' assert { type: 'json' };
export const TranscientEscrowContractArtifact = TranscientEscrowContractArtifactJson as ContractArtifact;

/**
 * Type-safe interface for contract TranscientEscrow;
 */
export class TranscientEscrowContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, TranscientEscrowContractArtifact, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, TranscientEscrowContract.artifact, wallet) as Promise<TranscientEscrowContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<TranscientEscrowContract>(Point.ZERO, wallet, TranscientEscrowContractArtifact, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(publicKey: PublicKey, wallet: Wallet, ) {
    return new DeployMethod<TranscientEscrowContract>(publicKey, wallet, TranscientEscrowContractArtifact, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TranscientEscrowContractArtifact;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** combineTwoEscrows(token: struct, amount1: field, randomness1: field, amount2: field, randomness2: field) */
    combineTwoEscrows: ((token: AztecAddressLike, amount1: FieldLike, randomness1: FieldLike, amount2: FieldLike, randomness2: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_nullifier(contract_address: field, nonce: field, storage_slot: field, preimage: array) */
    compute_note_hash_and_nullifier: ((contract_address: FieldLike, nonce: FieldLike, storage_slot: FieldLike, preimage: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** createEscrows(token: struct, amount1: field, nonce1: field, amount2: field, nonce2: field) */
    createEscrows: ((token: AztecAddressLike, amount1: FieldLike, nonce1: FieldLike, amount2: FieldLike, nonce2: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
